server:
  port: 9003

spring:
  application:
    name: carrito-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/carrito_service?serverTimezone=UTC
    username: root
    password: root

eureka:
  client:
    service-url.defaultZone: http://eureka:8761/eureka/

feign:
  usuarioapi:
    url: http://usuario-service:9001/