server:
  port: 9001

spring:
  application:
    name: usuario-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3308/usuario_service?serverTimezone=UTC
    username: admin
    password: 542345

eureka:
  client:
    service-url.defaultZone: http://localhost:8761/eureka/

