server:
  port: 9001

spring:
  application:
    name: usuario-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/usuario_service?serverTimezone=UTC
    username: root
    password: root

eureka:
  client:
    service-url.defaultZone: http://eureka:8761/eureka/

